### ISSUE TITLE
SyncedCron error with seed data

### ISSUE THREAD

**Issue by lnmunhoz** [sputlytics/sputlytics#19]
I cleared all my database and seeded the data again. The first attempt of the cronjob got this error:
```
I20160408-02:30:00.210(-3) (percolate_synced-cron.js:87) SyncedCron: Exception "Processing reports" TypeError: Cannot read property 'browser' of undefined
    at _.chain.map.countBy.map.name (lib/services/browserService.js:6:23)
    at packages/underscore.js:159:29
    at _.each._.forEach (packages/underscore.js:142:22)
    at Function._.map._.collect (packages/underscore.js:158:5)
    at [object Object]._.(anonymous function) [as map] (packages/underscore.js:1183:39)
    at Object.process (lib/services/browserService.js:5:8)
    at lib/collections/reports.js:57:39
    at Array.forEach (/Users/lnmunhoz/.meteor/packages/es5-shim/.4.5.9.7ovvxc++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:435:21)
    at lib/collections/reports.js:50:19
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1022:16)
```

**Comment by caio-ribeiro-pereira** [comment]
@lnmunhoz probably the seed is outdated, I'll check it

**Comment by caio-ribeiro-pereira** [comment]
@lnmunhoz did you check if this bug is fixed after you update the seeds??
